FROM ubuntu:latest

MAINTAINER Harsh Kasyap<harshkasyap@gmail.com>

RUN apt-get update && apt-get install -y npm && apt-get install -y git && apt-get clean

RUN mkdir /root/.ssh/
ADD id_rsa /root/.ssh/id_rsa
RUN chmod 700 /root/.ssh/id_rsa
RUN chown -R root:root /root/.ssh
RUN touch /root/.ssh/known_hosts
RUN ssh-keyscan github.com >> /root/.ssh/known_hosts
RUN git clone git@github.com:harshkasyap/FileServer.git
RUN apt-get remove -y git && apt-get -y autoremove
RUN rm -rf /root/.ssh
RUN npm --prefix FileServer i FileServer
CMD npm --prefix FileServer start

EXPOSE 5110

# Help and Instructions

# If you have docker installed, You can run this and have FileServer Up And Running
# docker run -p 5110:5110 --rm -v ShareLocation:/FileServer/Share -it harshkasyap/fileserver:v1.0
# Keep Your ShareLocation above where you want to keep the files.
# Ready to run in local Network as ip_address:5110


# And, If you want to build it locally with some custom modifications, Play with this dockerfile
# Pre-Requisites
# You should have ssh-keygen generated and public key addded with your github account
# keep id_rsa file in current folder having dockerfile
# docker build -t <image_name:tag> .
# Run it from where you have kept dockerfile. to build the docker image.
# docker run -p 5110:5110 --rm -v ShareLocation:/FileServer/Share -it <image_name:tag>
# Keep Your ShareLocation above where you want to keep the files.
# Ready to run in local Network as ip_address:5110

# You can change Host Port in either case in left side in docker ruun command. like 6000:5110